version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 8
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 038062473746.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build start on `date`
      - mvn clean install -DskipTests
      - mv target/petclinic.jar src/main/docker
      - cd client && npm install && npm test && npm run build:prod
      - docker build -t codebuild-frontend .
      - docker tag codebuild-frontend:latest 038062473746.dkr.ecr.us-east-1.amazonaws.com/codebuild-frontend:latest
      - cd ../src/main/docker 
      - docker build -t codebuild-backend .
      - docker tag codebuild-backend:latest 038062473746.dkr.ecr.us-east-1.amazonaws.com/codebuild-backend:latest
  post_build:
    commands:
      - docker push 038062473746.dkr.ecr.us-east-1.amazonaws.com/codebuild-backend:latest
      - docker push 038062473746.dkr.ecr.us-east-1.amazonaws.com/codebuild-frontend:latest
